### ISSUE TITLE
expected exceptions

### ISSUE THREAD

**Issue by sstirlin** [ActivisionGameScience/assertpy#41]
The Nim testrunner has a handy "expect" context that ensures that the expected exception is thrown.  It works like this:
```
  test "Making sure that this throws a RangeError":
    expect RangeError:
      var a = myArray[-1]
```

I'm wondering if something like this can be added to assertpy.  Right now the docs say to do this:
```
    try:
        some_func('bad arg')
        fail('should have raised error')
    except ValueError, ex:
        assert_that(ex.message).contains('some msg')
```

...But something like this might be nice:
```
    assert_that(some_func('bad arg')).raises(RuntimeError).with_message("some msg")
```

Or maybe this:
```
    assert_that(RuntimeError).is_raised_by(some_func('bad arg'))  # don't care about message
    assert_that(RuntimeError).is_raised_by(some_func('bad arg')).with_message("some msg")
```

**Comment by sstirlin** [comment]
pytest offers a "raises" context, obviously, but it doesn't read well (in my opinion)
```
with pytest.raises(SystemExit):
    f()
```

**Comment by saturnboy** [comment]
@sstirlin Without _deep_ magic it's not clear that you can capture a function invocation inline, wrap in `try..catch`, invoke, and then expect an exception.

Option 1:

```py
# 1a
assert_that(some_func).called_with_args('bad arg').raises(RuntimeError)

# 1b
assert_that(some_func).called_with('bad arg', 'other arg').raises(RuntimeError)

# 1c
assert_that(some_func).invoked_with('bad arg', 'other arg').raises(RuntimeError)
```

Option 2:

```py
with assert_raises(RuntimeError):
    some_func('bad arg')
```

Like any of those options? 1b is my favorite.

**Comment by jofusa** [comment]
i like the context manager, but that just might be py.test speaking

**Comment by sstirlin** [comment]
Yeah, I like one of the (1) options better (probably 1b).  Although I know that context managers are probably a more robust pattern, I don't think that they read well.

**Comment by saturnboy** [comment]
Let's try this out:

```py
assert_that(some_func).raises(RuntimeError).when_called_with('bad')
```

And that will chain the error message as the assertion value, so you can further verify with *any* assertion, like this:

```py
assert_that(some_func).raises(RuntimeError).when_called_with('bad').contains('err foo')
```

Of course order matters..

**Comment by sstirlin** [comment]
I like it.  Make it so, Number 1

**Comment by tappoz** [comment]
For whoever is not familiar with python and comes here trying to make this thing work after lots of different errors/exceptions:

- you just need to import one thing: `from assertpy import assert_that` (no need to import `raises` and all the others)
- then you import the module you want to test `import my_module.my_file` (maybe you need to hack `sys.path` if the directory `my_module` is sibling of the directory containing the tests)
- then you can use this "almost fluent" chain of calls (I think those ugly `\` backslashes are because of how python works internally when parsing the syntax, I don't think these can be avoided, but the code imho is more readable), one per line:

```python
assert_that(my_module.my_file.my_function_to_test)\
    .raises(ValueError)\
    .when_called_with("foo", 42, 42.0, "bar")\
    .is_length(123)\
    .starts_with('My error message')\
    .is_equal_to("My error message ... foo bar baz ..."))
```

I run all the tests with `python -m unittest discover -s my_test_directory_module/ -p *.py`

**Comment by saturnboy** [comment]
@tappoz thanks for the notes...

Here are docs [Expected Exceptions](https://github.com/ActivisionGameScience/assertpy#expected-exceptions), and examples [test_expected_exception.py](https://github.com/ActivisionGameScience/assertpy/blob/master/tests/test_expected_exception.py#L32)
